/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DEFAULT_XKB_LAYOUT "us"

#define DEFAULT_XKB_MODEL "pc105"

#define DEFAULT_XKB_RULES "evdev"

#define DFLT_XKB_CONFIG_ROOT "/usr/share/X11/xkb"

#define HAVE_EACCESS 1

#define HAVE_EUIDACCESS 1

#define HAVE_MKOSTEMP 1

#define HAVE_MMAP 1

#define HAVE_POSIX_FALLOCATE 1

#define HAVE_SECURE_GETENV 1

#define HAVE___BUILTIN_EXPECT 1

#define XLOCALEDIR "/usr/share/X11/locale"

#define _GNU_SOURCE 1

